# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'faker'

FlatReview.destroy_all
puts "Destroying flat reviews"
Booking.destroy_all
puts "Destroying bookings"
Flat.destroy_all
puts "Destroying flats"
Message.destroy_all
puts "Deleting messages"
UserReview.destroy_all
puts "Deleting User Reviews of Customers"
User.destroy_all
puts "Destroying users"

23.times do |user|
  name= Faker::Name.first_name
  email= Faker::Internet.email
  password= "azerty"
  avatar = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "andre",
  "matt",
  "17",
  "18",
  "19",
  "20",
  "21",
  "tom",
  "joan"
]
  q = avatar.sample
  avatar.delete_at(avatar.index(q))
#   user = User.create!(first_name:name, email:email, password:password,remote_photo_url="")
# end
  user = User.create!(first_name: name, email: email, password: password, avatar_data: "#{q}")
end

 puts "Create Thomas"
 User.create!(first_name:"Thomas", pseudo_g1:"tombrom", email:"test@test.fr", password:"azerty", avatar_data:"IMG-20181020-WA0000.jpg")
  
flats = [
  {
  title: "Charmante maison auvergnate traditionelle",
  description:"A 10 min de Clermont-Ferrand, maison en pierre volcanique, faîtou, 4 chambres, table de ping-pong, piscine etc",
  category:"maison",
  price_per_night:"3",
  street:"13, Nouvialle",
  city:"Narnhac",
  country:"France",
  zip_code:"15230",
  user_id: 1,
  image_data: "maison-pj.png, cheminee-cantal.jpg, cuisine-cantal.jpg, baignoire-pj.jpg",
  nb_beds: 3,
  nb_rooms: 3,
  nb_of_bathrooms:2,
  smoking: true
  },
  {title: "Appartement de caractère dans monument historique",
  description: "Joli appartement dans un village Mayennais de charme avec canapé-lit et possibilité d'avoir ma chambresi je ne suis pas présente.",
  category:"appartement",
  price_per_night:"7",
  street:"31 rue du Pavé",
  city:"Craon",
  country:"France",
  zip_code:"53400",
  user_id: 2,
  image_data: "garden4.jpg, chalet4.jpg, cuisine.jpg , bedroom9.jpg, cam.jpg",
  nb_beds: 4,
  nb_rooms: 2,
  smoking: true,
  nb_of_bathrooms: 2
  }, 
  {title: "2 chambres dans une maison avec jardin dans l'Orne",
  description: "Je propose 2 grandes chambres avec lits individuels dans ma maison, dans l'Orne. Un grand jardin vous attend, avec moutons et chevaux! Je cherche des personnes qui viendraient habiter chez moi et donneraient à manger à mes chats, surveilleraiengt moutons et chevaux, quand je pars, aux RML en particulier. Hébergement gratuit en retour à ces occasions.",
  category:"maison",
  price_per_night:"2",
  street:"La Bissonnerie",
  city:"Saint-Clair de Halouze",
  country:"France",
  zip_code:"61490",
  user_id: 2,
  image_data: "jardin2.jpg, jardin-mimi.jpg, cuisine-mimi.jpg, chambre3-mimi.jpg, chambre-mimi.jpg, sbd2-mimi.jpg, sdb-mimi.jpg, chambre2-mimi.jpg",
  nb_beds: 4,
  nb_rooms: 2,
  smoking: true,
  nb_of_bathrooms: 2
  }, 
  {title: "Chambre dans ma maison dans le Beaujolais",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"72 Impasse du Tracot",
  city:"Saint-Vérand",
  country:"France",
  zip_code:"69620",
  user_id: 5,
  image_data: "hong-lin-stoffels-1084565-unsplash",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  }, 
  {title: "2 Chambres dans mon duplex axe Lyon/Grenoble",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"appartement",
  price_per_night:"2",
  street:"Combe de Pommier",
  city:"Saint-Jean de Bournay",
  country:"France",
  zip_code:"38440",
  user_id: 5,
  image_data: "kalisa-veer-416292-unsplash.jpg, grove.jpg, cuisine.jpg, facade.jpg, appart2.jpg ",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  }, 
  {title: "2 Chambres dans maison avec grand jardin et piscine",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"23 chemin du Meraud",
  city:"Sainte-Blandine",
  country:"France",
  zip_code:"38110",
  user_id: 5,
  image_data: "bedroom10.jpg, bathroom6.jpg, bathroom2.jpg, bedroom1.jpg",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Terrain pour vos tentes, camping-car, fest-noz etc",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"44 route de montcarra",
  city:"Rochetoirin",
  country:"France",
  zip_code:"38440",
  user_id: 5,
  image_data: "tobias-weinhold-521143-unsplash.jpg, paul-hermann-777999-unsplash.jpg",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Superbe chalet pour vos vacances",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"1 Route de l'Eglise",
  city:"Saint-Didier-de-la-Tour",
  country:"France",
  zip_code:"38110",
  user_id: 5,
  image_data: "chalet2.jpg, chalet4.jpg, montagne.jpg",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "3 chambres avec lits doubles dans ma maison de plain-pied",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"526 Voie Louis Morel",
  city:"La Chapelle de la Tour", 
  country:"France",
  zip_code:"38110",
  user_id: 5,
  image_data: "chalet3.jpg, kitchen4.jpg, garden9.jpg, interieur.jpg, inside.jpg",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Camping-car pour vos vacances",
  description: "Camping-car permis B, couchage pour 4, CT récent, boîte 6, régulateur, chauffage, grande douche. Année: 2009",
  category:"camping-car",
  price_per_night:"2",
  street:"168 Chemin du Martin",
  city:"Artas",
  country:"France",
  zip_code:"38440",
  user_id: 5,
  image_data: "frankie-valentine-565054-unsplash.jpg, max-di-capua-984391-unsplash.jpg,carlos-hevia-628894-unsplash.jpg",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Chalet original à quelques minutes de Lyon et parc Miribel",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"4 rue du Coteau",
  city:"Saint-Maurice de Beynost",
  country:"France",
  zip_code:"01700",
  user_id: 5,
  image_data: "chalet3.jpg, chalet2.jpg, terrasse.jpg, garden2.jpg, chalet4.jpg, ",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Appartement complet, 60m2",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"16 Chemin des Brosses",
  city:"Genas",
  country:"France",
  zip_code:"69740",
  user_id: 5,
  image_data: "kalisa-veer-416292-unsplash.jpg",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "2 Chambres dans ma maison au calme, sud-est de Lyon",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"1444 Montée de Rognard",
  city:"Chaponnay",
  country:"France",
  zip_code:"69620",
  user_id: 5,
  image_data: "chalet3.jpg, garden.jpg, bedroom4.jpg, bedroom7.jpg, chalet.jpg ",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Maison entière pour les vacances à 1/2h de Lyon",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"11 Lotissement l'Orée du Village",
  city:"Marennes",
  country:"France",
  zip_code:"69970",
  user_id: 5,
  image_data: "cam.jpg, bedroom2.jpg, bedroom9.jpg, bathroom5.jpg, bathroom4.jpg, kitchen4.jpg",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Chambre dans ma maison entre Lyon et Grenoble",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"10 rue Justin Vernet",
  city:"La Tour du Pin",
  country:"France",
  zip_code:"38110",
  user_id: 5,
  image_data: "rober.jpg, kitchen.jpg, kitchen2.jpg, salon2.jpg",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Grande caravane moderne tout confort sur mon terrain à 20 min de Lyon",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"32 Avenue des Dauphins",
  city:"Corbas",
  country:"France",
  zip_code:"69960",
  user_id: 5,
  image_data: "vidar-nordli-mathisen-683072-unsplash.jpg, kitchen3.jpg",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Chambre dans mon appartement de Villeurbanne",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"23 cours Dr Jean  Damidot",
  city:"Villeurbanne",
  country:"France",
  zip_code:"69100",
  user_id: 5,
  image_data: "toe.jpg, salon2.jpg",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Chambre dans ma maison dans les monts du Lyonnais",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"8 rue de Bellevue",
  city:"Vaugneray",
  country:"France",
  zip_code:"69670",
  user_id: 5,
  image_data: "garden3.jpg, kitchen6.jpg, rob.jpg, interieur.jpg",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Terrain pour camping, caravane, camping-car, 5 min de Lyon",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"6 chemin de la Liasse",
  city:"Dardilly",
  country:"France",
  zip_code:"69570",
  user_id: 5,
  image_data: "",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Maison à Ecully",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"10bis chemin du Saquin",
  city:"Ecully",
  country:"France",
  zip_code:"69130",
  user_id: 5,
  image_data: "inside.jpg, grove.jpg, garden9",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Maison à Ecully",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"10bis chemin du Saquin",
  city:"Ecully",
  country:"France",
  zip_code:"69130",
  user_id: 5,
  image_data: "",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title: "Maison à Limonest",
  description: "Chambre avec cliclac et sanitaire. Lit bébé et table à langer déjà en place. Weekend et certaines vacances.",
  category:"maison",
  price_per_night:"2",
  street:"511 Chemin de Beluze",
  city:"Limonest",
  country:"France",
  zip_code:"69760",
  user_id: 5,
  image_data: "chambre-ludo.jpg",
  nb_beds: 1,
  nb_rooms: 1,
  smoking: true,
  nb_of_bathrooms: 2
  },
  {title:"Terrain avec étang proche de Saint-Etienne",
  description: "Grand terrain plat chez moi. Etang avec petite barque, possibilité de pécher, possibilité de prendre une douche à la maison",
  category:"terrain",
  price_per_night:"2",
  street:"30 rue Gabriel Péri",
  city:"Le Chambon-Feugerolles",
  country:"France",
  zip_code:"42500",
  user_id: 3,
  image_data: "paul-hermann-777999-unsplash.jpg, francesca.jpg, garden.jpg, bedroom2.jpg,bedroom4.jpg, bedroom6.jpg,",
  },
  {title:"Camping-Car sur mon terrain dans le Morbihan",
  description:"Camping-car Peugeot de 2000, m'en sers de temps en temps et est donc en bon état",
  category:"camping-car",
  price_per_night:"3",
  street:"2 Impasse des Chênes",
  city:"Séné",
  country:"France",
  zip_code:"56860",
  user_id: 4,
  image_data: "hanson-lu-481132-unsplash.jpg, outside.jpg, kitchen6.jpg, rober.jpg, sdb1.jpg, rob.jpg, kitchen2.jpg",
  nb_beds:4,
  smoking: true,
  nb_of_bathrooms: 3,
  },
  {title:"Caravane dans ma forêt personnelle",
  description:"Située dans les Landes, à Soustons, grande caravane avec auvent, petite piscine etc",category:"caravane",
  price_per_night:"4",
  street:"17 route de Tosse",
  city:"Soustons",
  country:"France",
  zip_code:"40140",
  user_id: 5,
  image_data: "vidar-nordli-mathisen-683072-unsplash.jpg, riccardo-mion-645217-unsplash.jpg,fyf5b8zmlt3nxdyuugng.jpg,
  ",
  nb_beds: 6,
  smoking: false,
  nb_of_bathrooms:2
  },
  {title:"Chambre dans ma maison à proximité de Toulouse",
  description:"Grande Chambre dans ma maison personnelle à Colomiers, proche de Toulouse. Maison avec piscine, salle  de bains privative, wifi etc. Je peux vous servir un bon ptit dej!",
  category:"maison",
  price_per_night:"3",
  street:"40 allée du Somport",
  city:"Colomiers",
  country:"France",
  zip_code:"31770",
  user_id: 1,
  image_data: "montagne.jpg, kitchen2.jpg, londres.jpg, matograine.jpg, chlqtvgopj4lgxq7q9e4.jpg, terrasse.jpg",
  nb_beds: 1,
  smoking: false,
  nb_of_bathrooms:1
  },
]

flats.each do |flat|
  puts "----"
  puts "creating a new logement"
  Flat.create!(flat)
  sleep 2
end
